# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/mainBD.xdc

# Block Designs: bd/mainBD/mainBD.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBD || ORIG_REF_NAME==mainBD} -quiet] -quiet

# IP: bd/mainBD/ip/mainBD_processing_system7_0_0/mainBD_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBD_processing_system7_0_0 || ORIG_REF_NAME==mainBD_processing_system7_0_0} -quiet] -quiet

# IP: bd/mainBD/ip/mainBD_clk_wiz_0_0/mainBD_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBD_clk_wiz_0_0 || ORIG_REF_NAME==mainBD_clk_wiz_0_0} -quiet] -quiet

# IP: bd/mainBD/ip/mainBD_axi_interconnect_0_0/mainBD_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBD_axi_interconnect_0_0 || ORIG_REF_NAME==mainBD_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/mainBD/ip/mainBD_xlconstant_0_0/mainBD_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBD_xlconstant_0_0 || ORIG_REF_NAME==mainBD_xlconstant_0_0} -quiet] -quiet

# IP: bd/mainBD/ip/mainBD_xadc_wiz_0_0/mainBD_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBD_xadc_wiz_0_0 || ORIG_REF_NAME==mainBD_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/mainBD/ip/mainBD_xlconstant_1_0/mainBD_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBD_xlconstant_1_0 || ORIG_REF_NAME==mainBD_xlconstant_1_0} -quiet] -quiet

# IP: bd/mainBD/ip/mainBD_axi_gpio_2_0/mainBD_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBD_axi_gpio_2_0 || ORIG_REF_NAME==mainBD_axi_gpio_2_0} -quiet] -quiet

# IP: bd/mainBD/ip/mainBD_xlconcat_0_0/mainBD_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBD_xlconcat_0_0 || ORIG_REF_NAME==mainBD_xlconcat_0_0} -quiet] -quiet

# IP: bd/mainBD/ip/mainBD_proc_sys_reset_0_1/mainBD_proc_sys_reset_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBD_proc_sys_reset_0_1 || ORIG_REF_NAME==mainBD_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/mainBD/ip/mainBD_axi_uart16550_0_0/mainBD_axi_uart16550_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBD_axi_uart16550_0_0 || ORIG_REF_NAME==mainBD_axi_uart16550_0_0} -quiet] -quiet

# IP: bd/mainBD/ip/mainBD_axi_uartlite_0_0/mainBD_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBD_axi_uartlite_0_0 || ORIG_REF_NAME==mainBD_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mainBD/ip/mainBD_xbar_0/mainBD_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBD_xbar_0 || ORIG_REF_NAME==mainBD_xbar_0} -quiet] -quiet

# IP: bd/mainBD/ip/mainBD_rst_ps7_0_100M_0/mainBD_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBD_rst_ps7_0_100M_0 || ORIG_REF_NAME==mainBD_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/mainBD/ip/mainBD_auto_pc_4/mainBD_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBD_auto_pc_4 || ORIG_REF_NAME==mainBD_auto_pc_4} -quiet] -quiet

# IP: bd/mainBD/ip/mainBD_auto_pc_0/mainBD_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBD_auto_pc_0 || ORIG_REF_NAME==mainBD_auto_pc_0} -quiet] -quiet

# IP: bd/mainBD/ip/mainBD_auto_pc_1/mainBD_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBD_auto_pc_1 || ORIG_REF_NAME==mainBD_auto_pc_1} -quiet] -quiet

# IP: bd/mainBD/ip/mainBD_auto_pc_2/mainBD_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBD_auto_pc_2 || ORIG_REF_NAME==mainBD_auto_pc_2} -quiet] -quiet

# IP: bd/mainBD/ip/mainBD_auto_pc_3/mainBD_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBD_auto_pc_3 || ORIG_REF_NAME==mainBD_auto_pc_3} -quiet] -quiet

# XDC: bd/mainBD/mainBD_ooc.xdc
