# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/sources/vivado/Sys_B_ref_design_Z7_10_V19_1/MatlabBuildRootTest1/MatlabBuildRootTest1.srcs/sources_1/bd/mainBD/ip/mainBD_xbar_0/mainBD_xbar_0.xci
# IP: The module: 'mainBD_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/sources/vivado/Sys_B_ref_design_Z7_10_V19_1/MatlabBuildRootTest1/MatlabBuildRootTest1.srcs/sources_1/bd/mainBD/ip/mainBD_xbar_0/mainBD_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mainBD_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/sources/vivado/Sys_B_ref_design_Z7_10_V19_1/MatlabBuildRootTest1/MatlabBuildRootTest1.srcs/sources_1/bd/mainBD/ip/mainBD_xbar_0/mainBD_xbar_0.xci
# IP: The module: 'mainBD_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/sources/vivado/Sys_B_ref_design_Z7_10_V19_1/MatlabBuildRootTest1/MatlabBuildRootTest1.srcs/sources_1/bd/mainBD/ip/mainBD_xbar_0/mainBD_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mainBD_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
